### ISSUE TITLE
Delayed Width Updates

### ISSUE THREAD

**Issue by wSedlacek** [tagZero/use-text-width#1]
Currently `useEffect` is used in `useTextWidth` which defers the update to the next render.

Using [useMemo](https://reactjs.org/docs/hooks-reference.html#usememo) or [useLayoutEffect](https://reactjs.org/docs/hooks-reference.html#uselayouteffect) should remove/reduce this delay so that there is less stuttering between renders.

**Comment by kkosmowski** [comment]
Hi, @erhangundogan @wSedlacek I would like to reopen this issue if possible as I believe these changes break the hook.

![image](https://user-images.githubusercontent.com/63412876/160594063-1643cf70-56fe-4c5e-8e77-d1901563f455.png)

In version 1.2.0 I am faced with `NaNpx` value for the element, with usage as below:

```tsx
  const inputRef = useRef<HTMLInputElement | null>(null);
  const inputWidth = useTextWidth({ ref: inputRef });

  //...

      <InputField
        inputRef={inputRef}
        //...
```

When I modify the code and React re–renders, the correct width is calculated.

**This issue does not happen in version 1.0.0**
