### ISSUE TITLE
ts-config target es6

### ISSUE THREAD

**Issue by mokapoka** [tagZero/use-text-width#3]
there is a reason for config target as es6 ?
it make some computability issues

I need to build es5 target , is it possible to change the ts-config target?

**Comment by erhangundogan** [comment]
Hey @mokapoka. There is no specific reason. I can change it to ES5 for the 1.2 version

**Comment by erhangundogan** [comment]
Please use v1.2.0 for ES5 compatibility https://github.com/tagZero/use-text-width/releases/tag/v1.2.0
