### ISSUE TITLE
ref option is not working properly

### ISSUE THREAD

**Issue by 20946nE** [tagZero/use-text-width#6]
Hello, I want to calc text width with ref option because I dont want to give static font and size to calculation. So I tried "ref" example in your library/examples but it logged `NaN` instead of actual width. Also same in my project. Because of your example has that issue, I dont need to provide any sandbox to you. You can check it from there.

**Comment by erhangundogan** [comment]
Hey @20946nE normally it should work. Double check what you are passing into `useTextWidth`. If you pass `undefined` or `empty text` inside `ref` then it won't work.

You can fork and play with [this example](https://codesandbox.io/s/tag0-use-text-width-pm76vk?file=/src/App.tsx:213-217). Just change `text` prop and it will show width underneath.

**Comment by adamatronix** [comment]
In your example it says Nan.
